'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabaseBrowser} from '../lib/supabase-browser';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1';
type View='dashboard'|'dna'|'score'|'careers'|'gaps'|'profile';
export default function StudentWorkspace({initial='dashboard'}:{initial?:View}){const [view,setView]=useState<View>(initial);const [profile,setProfile]=useState<any>();const [intel,setIntel]=useState<any>();const [careers,setCareers]=useState<any[]>([]);const [gaps,setGaps]=useState<any>();const [role,setRole]=useState('Data Analyst');const [whatIf,setWhatIf]=useState<any>();const [sql,setSql]=useState(75);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [resume,setResume]=useState('');
 const session=async()=>{const s=supabaseBrowser();return s?(await s.auth.getSession()).data.session:null};
 const get=async(path:string)=>{const s=await session();if(!s)throw new Error('Please sign in with Google to access the student workspace.');const r=await fetch(`${API}${path}`,{headers:{Authorization:`Bearer ${s.access_token}`}});if(!r.ok)throw new Error((await r.json()).detail||'Unable to load workspace');return r.json()};
 const load=async()=>{try{setLoading(true);const [p,i,c,g]=await Promise.all([get('/students/me/profile'),get('/students/me/intelligence'),get('/careers'),get(`/students/me/skill-gaps?role=${encodeURIComponent(role)}`)]);setProfile(p.profile);setIntel(i);setCareers(c.roles);setGaps(g)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[role]);useEffect(()=>{if(view==='dashboard'||view==='dna'||view==='score')load()},[view]);
 const projected=async()=>{try{setWhatIf(await get(`/careers/${encodeURIComponent(role)}/what-if?skill=SQL&target=${sql}`))}catch(e:any){setError(e.message)}};
 useEffect(()=>{if(view==='gaps')load()},[view]);
 const upload=async(file:File)=>{const s=await session();if(!s){setError('Please sign in before uploading a resume.');return}const fd=new FormData();fd.append('file',file);const r=await fetch(`${API}/resumes`,{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`},body:fd});if(r.ok){const j=await r.json();setResume(j.storage_path||j.path)}else setError('Resume upload failed. Use a valid PDF smaller than 5 MB.')};
 const logout=async()=>{const s=supabaseBrowser();if(s)await s.auth.signOut();location.href='/'};
 const nav=[['dashboard','Overview'],['dna','Career DNA'],['score','Market score'],['careers','Career explorer'],['gaps','Skill gaps'],['profile','Profile']];
 if(loading)return <div className="app-shell"><aside className="sidebar"><div className="brand">OMEN<span>.</span></div></aside><main className="main"><div className="card" style={{marginTop:40}}><div className="eyebrow">Student workspace</div><h1>Calculating your market position…</h1><p className="subtle">Connecting your profile, skills, and current market signals.</p></div></main></div>;
 if(error&&!profile)return <main className="landing"><section className="hero"><div className="eyebrow">Workspace unavailable</div><h1>We couldn’t load your <em>profile.</em></h1><p>{error}</p><Link href="/login" className="btn">Return to login</Link></section></main>;
 const score=intel?.score||0;const name=profile?.full_name||profile?.name||'Student';
 return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/student/dashboard">OMEN<span>.</span></Link><div><div className="eyebrow" style={{padding:'0 12px',marginBottom:8}}>Your workspace</div><nav className="nav">{nav.map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id as View)}>{label}</button>)}</nav></div><div className="sidebar-bottom"><b>{name}</b><br/>{profile?.department||'Student'} · {profile?.branch||''}<br/><br/><button className="btn secondary" onClick={logout}>Log out</button></div></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Authenticated student workspace</div><h1>{view==='dashboard'?`Good morning, ${name}.`:view==='dna'?'Your career DNA.':view==='score'?'Understand your market position.':view==='careers'?'Find your direction.':view==='gaps'?'Close the gap.':'Your profile.'}</h1><p>{profile?.career_intent||'Shape a career direction grounded in your actual signals.'}</p></div><div className="avatar">{name.slice(0,2).toUpperCase()}</div></header>{error&&<div className="card" style={{borderColor:'#e6b8ad',marginBottom:18}}><span className="negative">{error}</span></div>}
 {view==='dashboard'&&<section className="grid"><div className="card score-card"><div className="eyebrow" style={{color:'#a8d8b5'}}>Market employability score</div><div className="score-number">{score}<small>/ 100</small></div><div className="score-note">A market-derived readiness signal, not a hiring probability.</div><button className="btn secondary" style={{marginTop:20}} onClick={()=>setView('score')}>Why this score? →</button></div><div className="card wide"><h2>Score components</h2><div className="subtle">Signals calculated from your profile and market demand</div>{Object.entries(intel?.components||{}).map(([k,v]:any)=><div key={k}><div className="metric"><span>{k}</span><b>{v}</b></div><div className="bar"><i style={{width:`${v}%`}}/></div></div>)}</div><div className="card third"><h2>Top strengths</h2><div className="subtle">What is already working in your favor</div>{intel?.positives?.map((x:string)=><div className="factor positive" key={x}>{x}</div>)}<h2 style={{marginTop:24}}>Top gaps</h2>{intel?.gaps?.slice(0,3).map((x:string)=><div className="factor negative" key={x}>{x}</div>)}</div><div className="card two-thirds"><h2>Recommended next action</h2><div className="subtle">A focused move based on your current role fit</div><div style={{fontSize:25,fontWeight:800,margin:'18px 0 8px'}}>Improve {intel?.gaps?.[0]||'your next skill'}</div><p className="subtle">Open Skill gaps to see current level, required level, importance, and estimated effort.</p><button className="btn" onClick={()=>setView('gaps')}>View skill gap →</button></div></section>}
 {view==='dna'&&<section className="grid"><div className="card two-thirds"><h2>Career DNA</h2><div className="subtle">A visual profile built from your actual student signals.</div>{Object.entries(intel?.components||{}).slice(0,5).map(([k,v]:any)=><div key={k}><div className="metric"><span>{k}</span><b>{v}</b></div><div className="bar"><i style={{width:`${v}%`}}/></div></div>)}</div><div className="card third"><h2>Market positioning</h2><p className="subtle">Your current profile is compared with normalized market demand for the roles you explore. It is a readiness signal, not a promise of placement.</p><span className="pill">Target: {role}</span></div></section>}
 {view==='score'&&<section className="grid"><div className="card third"><div className="eyebrow">Current score</div><div className="score-number" style={{fontSize:66,color:'#1f6048'}}>{score}</div><p className="subtle">Market Employability Score</p></div><div className="card two-thirds"><h2>Score breakdown</h2><p className="subtle">Transparent contributors from the deterministic market-readiness engine.</p>{intel?.positives?.map((x:string)=><div className="factor positive" key={x}>{x}<b>positive contributor</b></div>)}{intel?.negatives?.map((x:string)=><div className="factor negative" key={x}>{x}<b>gap signal</b></div>)}<div style={{marginTop:18,padding:14,background:'#f8f3e9',borderRadius:10,fontSize:12}}>{intel?.methodology}</div></div></section>}
 {view==='careers'&&<section className="grid"><div className="card two-thirds"><h2>Career explorer</h2><div className="subtle">Select a role to inspect fit and skill gaps.</div>{careers.map((r:any)=><div className="role" key={r.role}><div className="role-head"><div><div className="role-title">{r.role}</div><span className="pill">{r.market_demand} demand</span></div><strong style={{fontSize:24}}>{r.match}%</strong></div><p>{r.description}</p><div className="tags">{r.missing_skills.map((x:string)=><span className="tag" key={x}>Gap · {x}</span>)}</div><button className="btn secondary" style={{marginTop:12}} onClick={()=>{setRole(r.role);setView('gaps')}}>View role gaps →</button></div>)}</div><div className="card third"><h2>Projected impact</h2><p className="subtle">What if you improve SQL from its current level to a target?</p><input type="range" min="0" max="100" value={sql} onChange={e=>setSql(Number(e.target.value))} style={{width:'100%',accentColor:'#1f6048'}}/><div className="metric"><span>SQL target</span><b>{sql}</b></div><button className="btn" onClick={projected}>Calculate projection</button>{whatIf&&<div style={{marginTop:18}}><span className="pill">Projected impact</span><div className="factor">Score <b>{whatIf.current_score} → {whatIf.projected_score}</b></div><div className="factor">{role} match <b>{whatIf.current_match}% → {whatIf.projected_match}%</b></div><p className="subtle">This is a projection, not a guaranteed placement outcome.</p></div>}</div></section>}
 {view==='gaps'&&<section className="grid"><div className="card two-thirds"><h2>{role} skill gaps</h2><div className="subtle">Required role skills minus your current profile.</div>{gaps?.gaps?.length?gaps.gaps.map((g:any)=><div className="role" key={g.skill}><div className="role-head"><div><div className="role-title">{g.skill}</div><span className={g.importance==='Critical'?'pill red':'pill warn'}>{g.importance}</span></div><strong>{g.gap} gap</strong></div><div className="metric"><span>Current {g.current} · Required {g.required}</span><b>{g.estimated_hours}h estimated</b></div><div className="bar"><i style={{width:`${Math.min(100,g.current/g.required*100)}%`}}/></div></div>):<div style={{padding:'30px 0'}} className="subtle">No gaps found for this role. Keep building verified evidence.</div>}</div></section>}
 {view==='profile'&&<section className="grid"><div className="card two-thirds"><h2>Profile</h2><div className="subtle">Profile edits persist through FastAPI and Supabase when configured.</div><div className="metric"><span>Name</span><b>{name}</b></div><div className="metric"><span>Department</span><b>{profile?.department||'—'}</b></div><div className="metric"><span>Branch / Semester</span><b>{profile?.branch||'—'} · {profile?.semester||'—'}</b></div><div className="metric"><span>CGPA / Backlogs</span><b>{profile?.cgpa||'—'} / {profile?.backlogs??'—'}</b></div><Link className="btn" href="/onboarding">Edit profile →</Link></div><div className="card third"><h2>Resume</h2><p className="subtle">Private PDF storage. Maximum 5 MB.</p><input type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/>{resume&&<div className="pill" style={{marginTop:15}}>Stored: {resume}</div>}</div></section>}
 </main></div>}
