-- Public reference data: authenticated users can read; only TPO/admin service workflows manage it.
alter table public.skills enable row level security; alter table public.roles enable row level security; alter table public.role_skills enable row level security; alter table public.companies enable row level security; alter table public.jobs enable row level security; alter table public.job_requirements enable row level security;
create policy skills_read_authenticated on public.skills for select to authenticated using (true); create policy skills_manage_tpo on public.skills for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy roles_read_authenticated on public.roles for select to authenticated using (true); create policy roles_manage_tpo on public.roles for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy role_skills_read_authenticated on public.role_skills for select to authenticated using (true); create policy role_skills_manage_tpo on public.role_skills for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy companies_read_authenticated on public.companies for select to authenticated using (true); create policy companies_manage_tpo on public.companies for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy jobs_read_authenticated on public.jobs for select to authenticated using (true); create policy jobs_manage_tpo on public.jobs for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy job_requirements_read_authenticated on public.job_requirements for select to authenticated using (true); create policy job_requirements_manage_tpo on public.job_requirements for all to authenticated using (public.is_tpo()) with check (public.is_tpo());

-- TPO-managed/system data.
alter table public.application_status_history enable row level security; alter table public.courses enable row level security; alter table public.course_phases enable row level security; alter table public.learning_resources enable row level security; alter table public.assessments enable row level security; alter table public.assessment_questions enable row level security; alter table public.market_snapshots enable row level security; alter table public.institutional_metrics enable row level security; alter table public.skill_gap_snapshots enable row level security;
create policy history_student_read on public.application_status_history for select to authenticated using (application_id in (select id from applications where student_id in (select id from student_profiles where user_id=auth.uid()))); create policy history_tpo_manage on public.application_status_history for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy courses_read_authenticated on public.courses for select to authenticated using (true); create policy courses_manage_tpo on public.courses for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy phases_read_authenticated on public.course_phases for select to authenticated using (true); create policy phases_manage_tpo on public.course_phases for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy resources_read_authenticated on public.learning_resources for select to authenticated using (true); create policy resources_manage_tpo on public.learning_resources for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy assessments_read_authenticated on public.assessments for select to authenticated using (true); create policy assessments_manage_tpo on public.assessments for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy questions_read_authenticated on public.assessment_questions for select to authenticated using (true); create policy questions_manage_tpo on public.assessment_questions for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy market_read_authenticated on public.market_snapshots for select to authenticated using (true); create policy market_manage_tpo on public.market_snapshots for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy metrics_read_tpo on public.institutional_metrics for select to authenticated using (public.is_tpo()); create policy metrics_manage_tpo on public.institutional_metrics for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy gaps_read_tpo on public.skill_gap_snapshots for select to authenticated using (public.is_tpo()); create policy gaps_manage_tpo on public.skill_gap_snapshots for all to authenticated using (public.is_tpo()) with check (public.is_tpo());

-- Student-owned learning, resumes, experience and projects.
alter table public.student_course_progress enable row level security; alter table public.student_assessment_attempts enable row level security; alter table public.skill_verifications enable row level security; alter table public.resumes enable row level security; alter table public.certifications enable row level security; alter table public.experiences enable row level security; alter table public.career_role_matches enable row level security; alter table public.student_skill_gaps enable row level security; alter table public.student_job_matches enable row level security;
create policy progress_own on public.student_course_progress for all to authenticated using (student_id in (select id from student_profiles where user_id=auth.uid())) with check (student_id in (select id from student_profiles where user_id=auth.uid()));
create policy attempts_own on public.student_assessment_attempts for all to authenticated using (student_id in (select id from student_profiles where user_id=auth.uid())) with check (student_id in (select id from student_profiles where user_id=auth.uid()));
create policy verification_read_own on public.skill_verifications for select to authenticated using (student_id in (select id from student_profiles where user_id=auth.uid()) or public.is_tpo()); create policy verification_manage_tpo on public.skill_verifications for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy resumes_own on public.resumes for all to authenticated using (student_id in (select id from student_profiles where user_id=auth.uid()) or public.is_tpo()) with check (student_id in (select id from student_profiles where user_id=auth.uid()) or public.is_tpo());
create policy certifications_own on public.certifications for all to authenticated using (student_id in (select id from student_profiles where user_id=auth.uid())) with check (student_id in (select id from student_profiles where user_id=auth.uid()));
create policy experiences_own on public.experiences for all to authenticated using (student_id in (select id from student_profiles where user_id=auth.uid())) with check (student_id in (select id from student_profiles where user_id=auth.uid()));
create policy role_matches_own on public.career_role_matches for select to authenticated using (student_id in (select id from student_profiles where user_id=auth.uid()) or public.is_tpo());
create policy skill_gaps_own on public.student_skill_gaps for select to authenticated using (student_id in (select id from student_profiles where user_id=auth.uid()) or public.is_tpo());
create policy job_matches_own on public.student_job_matches for select to authenticated using (student_id in (select id from student_profiles where user_id=auth.uid()) or public.is_tpo());

-- TPO-managed outcomes and bootcamp/poll workflows.
alter table public.placement_results enable row level security; alter table public.bootcamps enable row level security; alter table public.bootcamp_enrollments enable row level security; alter table public.student_polls enable row level security; alter table public.poll_options enable row level security; alter table public.poll_responses enable row level security;
create policy results_student_read on public.placement_results for select to authenticated using (application_id in (select id from applications where student_id in (select id from student_profiles where user_id=auth.uid())) or public.is_tpo()); create policy results_tpo_manage on public.placement_results for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy bootcamps_read_authenticated on public.bootcamps for select to authenticated using (true); create policy bootcamps_manage_tpo on public.bootcamps for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy enrollments_own on public.bootcamp_enrollments for select to authenticated using (student_id in (select id from student_profiles where user_id=auth.uid()) or public.is_tpo()); create policy enrollments_manage_tpo on public.bootcamp_enrollments for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy polls_read_authenticated on public.student_polls for select to authenticated using (active=true or public.is_tpo()); create policy polls_manage_tpo on public.student_polls for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy poll_options_read_authenticated on public.poll_options for select to authenticated using (true); create policy poll_options_manage_tpo on public.poll_options for all to authenticated using (public.is_tpo()) with check (public.is_tpo());
create policy poll_responses_own on public.poll_responses for all to authenticated using (student_id in (select id from student_profiles where user_id=auth.uid())) with check (student_id in (select id from student_profiles where user_id=auth.uid())); create policy poll_responses_tpo_read on public.poll_responses for select to authenticated using (public.is_tpo());
