alter table public.courses add column if not exists prerequisites text[] not null default '{}';
alter table public.courses add column if not exists target_roles text[] not null default '{}';
alter table public.courses add column if not exists status text not null default 'published';
alter table public.course_phases add column if not exists is_required boolean not null default true;
alter table public.learning_resources add column if not exists description text;
alter table public.learning_resources add column if not exists duration_minutes int;
alter table public.learning_resources add column if not exists resource_order int not null default 0;
alter table public.assessments add column if not exists description text;
alter table public.assessments add column if not exists passing_score numeric(5,2) not null default 70;
alter table public.assessments add column if not exists estimated_minutes int;
alter table public.assessment_questions add column if not exists question_type text not null default 'mcq';
alter table public.projects add column if not exists course_id uuid references public.courses(id);
alter table public.projects add column if not exists project_kind text not null default 'final';
alter table public.projects add column if not exists objective text;
alter table public.projects add column if not exists requirements text[] not null default '{}';
alter table public.projects add column if not exists expected_output text;
alter table public.projects add column if not exists required_skills jsonb not null default '[]';
alter table public.projects add column if not exists submitted_at timestamptz;
alter table public.projects add column if not exists verified_by uuid references public.profiles(id);
alter table public.projects add column if not exists verified_at timestamptz;
alter table public.projects add column if not exists verification_status text not null default 'Not Started';
alter table public.projects add column if not exists assessment_id uuid references public.assessments(id);
alter table public.student_assessment_attempts add column if not exists attempt_number int not null default 1;
alter table public.student_assessment_attempts add column if not exists answers jsonb not null default '{}';
alter table public.student_assessment_attempts add column if not exists passed boolean not null default false;
alter table public.student_assessment_attempts add column if not exists started_at timestamptz default now();
alter table public.student_assessment_attempts add column if not exists submitted_at timestamptz;
create index if not exists projects_status_idx on public.projects(status,verification_status);
create index if not exists attempts_assessment_student_idx on public.student_assessment_attempts(assessment_id,student_id);
